### PR TITLE
Point Source0 to GitHub

### PR DESCRIPTION
**Pull request by cnsnyder**
This updates the spec file Source to point to GitHub released tar.gz files.

### CODE REVIEW

**Comment by evgeni** [comment]
I'd argue that having `%{release}` in the tarball name is wrong, as `%{release}` contains also the disttag, and here I end up with `virt-who-0.20.2-1.fc26.tar.gz`.

**Comment by evgeni** [comment]
I think we can just hard-code `-1` here, as we only care for the main source, which should not change between revisions (the spec will, but that's outside the tarball).

**Comment by cnsnyder** [comment]
@evgeni By hard code, do you mean to update the Source0 whenever we produce a new build?

**Comment by evgeni** [comment]
No, I mean setting:
```
Source0:        https://codeload.github.com/%{name}/%{name}/tar.gz/%{name}-%{version}-1#/%{name}-%{version}.tar.gz
```
This will:
* download the code from codeload.g.c (thus saving a redirect which some downloaders don't like)
* name the file `%{name}-%{version}.tar.gz` without any `-%{release}` in it
* always fetch the tarball of the first dist-revision (`-1`) of a release

I think that unconditionally getting the `-1` revision for `Source0` is OK, as we only care for the main `virt-who` code here. Any further revision would maybe change the spec file or add patches (as further sources) but should never touch the main source.

**Comment by evgeni** [comment]
Or we create a macro `%{release_number}` and use that like pulp does: https://github.com/pulp/pulp/blob/master/pulp.spec#L49

**Comment by cnsnyder** [comment]
Updated based on feedback to mimic the way pulp handles release_number

**Comment by evgeni** [comment]
Can you add `#/%{name}-%{version}.tar.gz` to the `Source0` URL? That will allow the downloader to rename the file properly, otherwise it would be called `%{git_tag}`.

**Comment by evgeni** [comment]
:+1: LGTM!

**Comment by cnsnyder** [comment]
Merging, test failures are errors not failures and not due to these changes.

**Pull request merged**
