### PR TITLE
1708534: add kubeconfig to template

### PR DESCRIPTION
**Pull request by pkliczewski**
We need to make configuration template complete. kubeconfig option was
missing and it was added to the file.

Fixes: https://bugzilla.redhat.com/1708534

### CODE REVIEW

**Comment by wottop** [comment]
ack

**Comment by wottop** [comment]
commit message should begin with the bug number.

1708534: ....

**Comment by pkliczewski** [comment]
@wottop PR and commit names updated

**Comment by wottop** [comment]
ack

**Pull request merged**
