### PR TITLE
1575513: Re-add changelog entries that were merged out.

### PR DESCRIPTION
**Pull request by wottop**

### CODE REVIEW

**Comment by cnsnyder** [comment]
@wottop This looks good to me. We should get Igor's opinion as well to better understand his intentions.

My only question would be, should we change the URL and Source0 back to upstream fedora?

**Comment by igor-raits** [comment]
this is not enough. you've re-added BuildRoot , %clean also.

**Comment by wottop** [comment]
Removed build root and clean. Updated URL and Source0

**Comment by kahowell** [comment]
@ignatenkobrain how does it look now? Also are there any documents which recommend practices for maintaining the spec file in upstream repository? Otherwise, I'd like to discuss what the best practices and processes for maintenance of virt-who and other candlepin-related projects in Fedora is (maybe such a doc could be produced as a result)?

**Comment by igor-raits** [comment]
> how does it look now?

lgtm

> Also are there any documents which recommend practices for maintaining the spec file in upstream repository?

Recomendation is not to. Or you can do this, but anytime you push into fedora git, you need to check all changes and not overwrite them.

**Comment by kahowell** [comment]
@ignatenkobrain ack. We will plan to modify our process to regularly incorporate changes from Fedora git into upstream.

**Pull request merged**
