### PR TITLE
kubevirt support

### PR DESCRIPTION
**Pull request by pkliczewski**
This PR provides support for kubevirt. In order to use it we expect
standard KUBECONFIG env variable to be set. This approach is similar to
other kubernetes/kubevirt clients.

### CODE REVIEW

**Comment by pkliczewski** [comment]
@fabiand please review

**Comment by pkliczewski** [comment]
This PR depends on https://github.com/kubevirt/client-python/issues/11

**Comment by fabiand** [comment]
Wow. At a first glance this looks pretty straight forward.

But I cant do a deep review right now.

/cc @vladikr

**Comment by wottop** [comment]
@fabiand @pkliczewski 
Are the TODO's something that we will see soon? Are you expecting the PR to be merged before they are complete? What is the plan?
It would be better to have tests to ensure we haven't broken anything will these changes.

thanks

**Comment by pkliczewski** [comment]
@wottop Tests added to the PR

**Comment by xsgordon** [comment]
Looks good from my POV if I am understanding correctly (appears to match intent). Requires technical review.

**Comment by wottop** [comment]
I have looked it over and have asked @cnsnyder to do the same.

**Review by cnsnyder — APPROVED** [review]
Looks great! Thank you for your contribution!

**Comment by wottop** [comment]
I will merge this tomorrow AM (9:00 EST) if I do not get any objections.

**Pull request merged**
